### ISSUE TITLE
use image_transport instead of publishing images directly

### ISSUE THREAD

**Issue by juergensturm** [Intermodalics/tango_ros#100]
http://wiki.ros.org/image_transport
This gives more flexibility to the client whether or not to get compressed images (and to what degree). This is a very small change in code.

**Comment by PerrineAguiar** [comment]
I tried using image_transport but did not manage to make it work.
When creating a new [CameraPublisher](https://github.com/ros-perception/image_common/blob/hydro-devel/image_transport/include/image_transport/camera_publisher.h), an exception is thrown. After looking at the image transport code, I found that it comes from [here](https://github.com/ros-perception/image_common/blob/hydro-devel/image_transport/src/publisher.cpp#L126).

In the [ros wiki](http://wiki.ros.org/image_transport_plugins), they mentioned: _These transports will only be available if the plugins are built on your system!_ So that may be the cause.
I remember @adamantivm also mentioned this in https://github.com/Intermodalics/tango_ros/issues/3#issuecomment-263296703.

**Comment by juergensturm** [comment]
Ok, got it. Let's see whether Julian has a solution.
