### ISSUE TITLE
Allow to run roscore inside the app

### ISSUE THREAD

**Issue by PerrineAguiar** [Intermodalics/tango_ros#127]

**Comment by PerrineAguiar** [comment]
@adamantivm Do you have an example on how to this?

**Comment by jubeira** [comment]
@PerrineAguiar the default MasterChooser has an option to do this. Look for the method `onActivityResult` inside `RosActivity`, there is a codepath that starts a new master there. Hope it helps!

**Comment by PerrineAguiar** [comment]
@jubeira Thanks for pointing me in the right direction.

**Comment by adamantivm** [comment]
Sorry I'm a bit swamped travelling at the moment. Thank you @jubeira for the pointer to @PerrineAguiar.

BTW, at some point it would be nice to generalize this "alternate master chooser" model so that new rosjava apps can get this type of behavior by default or as an alternative to the master chooser.
