### ISSUE TITLE
Make basic tutorial rviz tutorial

### ISSUE THREAD

**Issue by PerrineAguiar** [Intermodalics/tango_ros#186]

**Comment by PerrineAguiar** [comment]
I added the tutorial here: http://wiki.ros.org/tango_ros_streamer/Visualisation
@smits @jubeira @adamantivm @juergensturm Any comments to improve it is welcomed.

**Comment by juergensturm** [comment]
Super cool, I love this. It's also great to see that the point cloud overlay to images works :+1: 

Just one very minor suggestion:
Although all the information is provided, people might find it hard to re-create the settings in RViz. Do you think you could summarize the most important ones (and for support, offer them the rviz file)? And/or I would suggest to unfold the Rviz settings so that people can see them in the screenshot (the config on the left, showing the properties of the relevant displays).

![image](https://cloud.githubusercontent.com/assets/14937383/24751594/7d86088a-1aca-11e7-857a-830b3e530ee7.png)

**Comment by PerrineAguiar** [comment]
@juergensturm Thanks for your suggestion. We already give a link to the rviz file, but it is good idea to unfold the Rviz settings. I'll update the picture.
