### ISSUE TITLE
Forward Tango Error/Warning/Info logcat messages to /rosout

### ISSUE THREAD

**Issue by PerrineAguiar** [Intermodalics/tango_ros#59]

**Comment by PerrineAguiar** [comment]
@adamantivm I remember you were mentioning this once. Can you point me somewhere so I can start working on this?

**Comment by adamantivm** [comment]
I'm a bit tied up at the moment and can't dig in more detail but just in case this helps: I think that when you import rosjava you get Apache Commons Logging as a dependency. If you log with that instead of the default Android logger, I think the output will end up both in the logcat and in rosout, which is a nice side-effect.
Let me know if you can't get that to work and I'll dig in more detail (later when I have a chance).

**Comment by PerrineAguiar** [comment]
@adamantivm Thanks for the pointer!
